---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'sql/**'
      - 'systemd/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'sql/**'
      - 'systemd/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            meson \
            libsystemd-dev \
            libdbus-1-dev \
            libseccomp-dev \
            libfmt-dev \
            libcurl4-openssl-dev \
            libcap-dev \
            libgtest-dev \
            libpq-dev

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v

      - name: Unit Tests
        run: meson test -C output

      - name: Dump Unit Test Log
        if: ${{ failure() }}
        continue-on-error: true
        run: cat output/meson-logs/testlog.txt
