---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'sql/**'
      - 'systemd/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'sql/**'
      - 'systemd/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            libfmt-dev \
            libsystemd-dev \
            libdbus-1-dev \
            libseccomp-dev \
            libcurl4-openssl-dev \
            libcap-dev \
            libgtest-dev \
            libpq-dev

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{github.job}}

      - name: Configure
        run: |
          meson setup \
            -Dauto_features=enabled \
            -Ddocumentation=disabled \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v

      - name: Unit Tests
        run: meson test -C output --print-errorlogs

  mini:
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            libfmt-dev \
            libcurl4-openssl-dev \
            libgtest-dev \
            libpq-dev

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{github.job}}

      - name: Configure
        run: |
          meson setup \
            -Dauto_features=disabled \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v

      - name: Unit Tests
        run: meson test -C output --print-errorlogs
